### ISSUE TITLE
Cursor error with XBox Series Controller

### ISSUE THREAD

**Issue by x51mon** [roxgib/anki-contanki#11]
An joystick with the cursor option set on a XBox Series controller shows an error message (as a tool tip) when using it:
`Error: setX(self, int): argument 1 has unexpected type 'float'`.

**Comment by roxgib** [comment]
Thanks for reporting this. That function has never complained about accepting a float for me so I dunno what's different for you, but I've added a cast to int which should fix the problem. 

 If you wouldn't mind, could you:
- try [this version](https://github.com/roxgib/anki-contanki/files/9194640/contanki.ankiaddon.zip) to confirm that it's fixed? 
- Let me know what OS and Anki version you're using? I would have expected to pick this up in my own testing.

**Comment by roxgib** [comment]
Beta 6 is now on published with this fixed. Thanks for reporting it!
