### ISSUE TITLE
[Duelsense/PS5 controller] Mapping issues

### ISSUE THREAD

**Issue by mobedoor** [roxgib/anki-contanki#13]
Hello. Except for the D-Pad keys, none of the keys are correctly mapped.
https://gamepad-tester.com/ shows correct mappings for my controller.
Help would be appreciated.
Thank you.

anki-contanki Beta5
EndeavourOS

**Comment by roxgib** [comment]
Thanks for reporting this, I'll try to reproduce on my end.

**Comment by mobedoor** [comment]
Hi. Issue is fixed on my end after reinstalling linux. Must've had some configuration issue.
