### ISSUE TITLE
Can You add an option to turn off Dualshock 4 light? Just to reserve some battery

### ISSUE THREAD

**Issue by AbdelrahmanHamdy1998** [roxgib/anki-contanki#15]
![image](https://user-images.githubusercontent.com/79529298/182392406-dce785ac-6ee4-4931-8f89-d34d608cacfd.png)

**Comment by roxgib** [comment]
Yeah this annoys me too, but unfortunately the API doesn't support controlling the light. It's possible with other software - on Windows DS4Windows lets you turn off the light and on Mac (and Windows) it can be done with Steam. Not super convenient but it does work.
