### ISSUE TITLE
Latest update (2022-08-02) has broken the add-on

### ISSUE THREAD

**Issue by jjp87** [roxgib/anki-contanki#16]
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Contanki - Controller Support for Anki beta⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 230, in loadAddons
  File "C:\Users\james\AppData\Roaming\Anki2\addons21\1898790263\__init__.py", line 2, in <module>
    from .contanki import Contanki
  File "C:\Users\james\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 12, in <module>
    from .config import *
  File "C:\Users\james\AppData\Roaming\Anki2\addons21\1898790263\config.py", line 506, in <module>
    class CustomActions(QWidget):
  File "C:\Users\james\AppData\Roaming\Anki2\addons21\1898790263\config.py", line 508, in CustomActions
    self, parent: ContankiConfig, tab: QWidget, actions: dict[str, str]
TypeError: 'type' object is not subscriptable
⁩

**Comment by roxgib** [comment]
Thanks for reporting this. I'm not able to reproduce but I've added the annotations import to all the python files which should resolve the problem anyway. I'll push the fix out shortly.

**Comment by roxgib** [comment]
BTW, can I ask what Anki version you're using?

**Comment by roxgib** [comment]
I've just published a new release - could you confirm that the problem has been resolved?

**Comment by jjp87** [comment]
Version ⁨2.1.49 (dc80804a)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

Just installed new release, seems to be working smoothly now. 
Thank you very much for the great add-on and I appreciate you fixing so quickly!

**Comment by roxgib** [comment]
> Version ⁨2.1.49
> Python 3.8.6

Apparently I skipped the tests for pre-50 versions of Anki, which use a previous version of Python - oops! Thanks for letting me know!
