### ISSUE TITLE
Removing custom actions

### ISSUE THREAD

**Issue by kenf1** [roxgib/anki-contanki#18]
Previously saved custom actions aren't able to be deleted from Options menu after clicking "Delete" -> "Save". No luck with closing and reopening Anki.

Circumvented bug by removing and reinstalling/reconfiguring addon.

OS: macOS
Anki version: ⁨2.1.54 (Apple Silicon Qt6)

**Comment by roxgib** [comment]
Thanks reporting this, it will be fixed in the next beta ([040364b](https://github.com/roxgib/anki-contanki/commit/040364b9366f047b9c89f8d039960c620ad55cab))
