### ISSUE TITLE
Does not work with 2.1.51 RC

### ISSUE THREAD

**Issue by Acuelatus** [roxgib/anki-contanki#2]
The add-on works like a charm in anki 2.1.50 but with the 2.1.51 RC does not work.

**Comment by roxgib** [comment]
Thanks for the report, I haven't gotten to do any testing with 2.1.51 yet. Can you say what platform you're on and whether you're using the Qt5 or Qt6 version?

**Comment by roxgib** [comment]
No worries then, let me know if it happens again. FYI I'm adding buttons for the 8BitDo Zero and Lite in update soon.
