### ISSUE TITLE
Scroll up and down customization

### ISSUE THREAD

**Issue by Sartopia** [roxgib/anki-contanki#21]
Hey man thanks for the awesome anki controller support
I happen to have a problem with it, im using 8bit zero 2, and the scroll up and down action is broken:
In short, it doesnt scroll when i press the button it goes all the way down or all the way up 
And i didnt find any option to tune it down, the « scroll speed » option doesnt change anything

is there a way to fix this ?
Thanks and sorry i posted this question here and on anki i didnt really know where is the best place to submit issue

**Comment by salami95** [comment]
I am also having this happen. It won't keep me from using the addon, but it would be nice to scroll through a lengthy card slowly.

**Comment by roxgib** [comment]
Thanks, and sorry for the delay in responding. I believe I know what's causing this and I'll aim to have it fixed in the next beta.

**Comment by roxgib** [comment]
The behaviour should be improved in the new beta, although I haven't gotten around to adding customisation.

**Comment by roxgib** [comment]
Scroll speed of buttons is linked to the overall screen speed setting now, which should provide sufficient customisation
