### ISSUE TITLE
Disconnecting Xbox One controller crashes Contanki and requires Anki restart

### ISSUE THREAD

**Issue by dborsuk** [roxgib/anki-contanki#22]
Anytime the Xbox One controller disconnects (either manually or auto-off shutdown), I get the error below. This either occurs immediately or after reconnecting the controller and going back into Anki.

Also, my Xbox One controller is recognized as an Xbox 360 controller, haven't been able to change the profile.

> Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
> Debug info:
> Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
> Platform: Mac 12.5
> Flags: frz=True ao=True sv=2
> Add-ons, last update check: 2022-09-08 12:53:58
> Add-ons possibly involved: ⁨Contanki - Controller Support for Anki beta⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt.webview", line 42, in cmd
>   File "aqt.webview", line 149, in _onCmd
>   File "aqt.webview", line 618, in _onBridgeCmd
>   File "aqt.hooks_gen", line 4358, in __call__
>   File "/Users/dborsuk/Library/Application Support/Anki2/addons21/1898790263/contanki.py", line 122, in on_receive_message
>     funcs[func](*args)
>   File "/Users/dborsuk/Library/Application Support/Anki2/addons21/1898790263/contanki.py", line 63, in on_connect
>     self.mods = [False] * len(self.profile.mods)
> AttributeError: 'NoneType' object has no attribute 'mods'

**Comment by roxgib** [comment]
Thanks for the report. The crash should be fixed in the latest Alpha release, which includes addresses a number of connection related issues, although note that a lot of code has changed so there may be other bugs. This should be fixed in an upcoming beta, hopefully some time next week.

**Comment by roxgib** [comment]
Would you be willing to try the [latest beta release](https://github.com/roxgib/anki-contanki/releases/download/v0.8.1-beta/contanki.ankiaddon) and let me know if the issue still occurs?

**Comment by dborsuk** [comment]
Yes, just tried it. It appears the issue is gone! I'll let you know if it reappears.
