### ISSUE TITLE
Trying to setup the "Joy-Con" profile results in Anki throwing an error

### ISSUE THREAD

**Issue by afshida** [roxgib/anki-contanki#25]
Trying to create a new profile for the right joycon using the pre-existing Joy-Con template profile so that I can use the trigger buttons. However, when trying to modify the JoyCon profile, the following error is thrown. 

Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 12.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-14 09:46:34
Add-ons possibly involved: ⁨Contanki - Controller Support for Anki beta⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Anki2/addons21/1898790263/config.py", line 425, in refresh_options
    self.setup_options()
  File "/Users/user/Library/Application Support/Anki2/addons21/1898790263/config.py", line 304, in setup_options
    button.setCurrentText(self.profile.axes_bindings[axis])
KeyError: 2

**Comment by afshida** [comment]
This is using the most recently published version from AnkiWeb (10-14-2022)

**Comment by roxgib** [comment]
Thanks for reporting this, would you mind trying the latest beta on GitHub - https://github.com/roxgib/anki-contanki/releases/tag/v0.8.1-beta

**Comment by afshida** [comment]
Same issue with the beta:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 12.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-16 14:32:18
Add-ons possibly involved: ⁨Contanki - Controller Support⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Anki2/addons21/contanki/config.py", line 379, in update_controller
    self.reload()
  File "/Users/user/Library/Application Support/Anki2/addons21/contanki/config.py", line 174, in reload
    self.options_page.update()
  File "/Users/user/Library/Application Support/Anki2/addons21/contanki/config.py", line 293, in update
    self.axis_roles.setup()
  File "/Users/user/Library/Application Support/Anki2/addons21/contanki/config.py", line 550, in setup
    dropdown.setCurrentText(self.profile.axes_bindings[axis])
KeyError: 2

**Comment by afshida** [comment]
Also, as a general feature request, I would love for the ability to use the trigger buttons when using one-handed joycon mode (i.e. ZR and R buttons in addition to the SR and SL buttons for the Joy-Con Right Profile). I am encountering this error, because I want to use the Joycon profile- which still has these buttons available- while using just my right joycon.

**Comment by roxgib** [comment]
Oh, I see the issue now. It'll be fixed in the next beta.

> I would love for the ability to use the trigger buttons when using one-handed joycon mode

I'll look into this - I've had it on my todo list to borrow a pair of joy-cons from a friend for testing, I might be able to do this if I have access to them, but I'm not sure if those buttons are actually active when only one is connected.

**Comment by afshida** [comment]
I am pretty sure they are, using another app, JoyKeyMapper, i was able to use the triggers as my default for flipping cards, the problem with that app is that it randomly disconnects. Your's is significantly more stable. 

The workaround i'm using now is nbd though.

Also the Quick Select is an awesome implementation, It would be nice to be able to use both Left and Right sticks to select from the options though (as opposed to just Left Stick). I was looking around your code, and I'm wondering if I change line 91 in contanki.py to "Right Stick" instead of the Left Stick, would that achieve what I want?

**Comment by roxgib** [comment]
> I am pretty sure they are, using another app, JoyKeyMapper

It may depend on the implementation of the HTML5 Gamepad API. Anki's graphics toolkit uses WebKit (i.e. Safari) on Mac and Chromium on Windows and Linux, so the same controller may be treated differently on different platforms. I'm looking at collecting donations so I can buy more controllers for testing, although most controllers work fine, it's just something like Joy-Cons which can behave a little weirdly. 

> Also the Quick Select is an awesome implementation, 

Thanks! 

> It would be nice to be able to use both Left and Right sticks to select from the options though (as opposed to just Left Stick). I was looking around your code, and I'm wondering if I change line 91 in contanki.py to "Right Stick" instead of the Left Stick, would that achieve what I want?

That'll only change the icon, it actually just picks the first two axes (which is usually the left stick). I'll probably make it use both sticks, it was just easier to pick one stick, but some controllers implement their dpads as axes which has made it a bit complicated. But I'd expect that change to be in a future version.

**Comment by roxgib** [comment]
@afshida On the latest version it should now be possible to assign actions to all the buttons when a single Joy-Con is connected
