### ISSUE TITLE
Not working after 10/23 update 

### ISSUE THREAD

**Issue by al099** [roxgib/anki-contanki#28]
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-23 09:49:56

1 controller detected:
Joy-Con (L) (STANDARD GAMEPAD Vendor: 057e Product: 2006)
Buttons: 17
Axes: 2

Hello, after updating my previous button mapping settings were erased. After setting it up again, it didn't save after I restarted anki or every time the controller disconnects and reconnects. Is there a way I can install the previous version before the update? It messed up many of my reviews :(

**Comment by al099** [comment]
I tried deleting and reinstalling the newest update again from Ankiweb. But now it doesn't show up in the Tools column and when I hit Config I see this:
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-23 10:08:01
Add-ons possibly involved: ⁨Contanki - Controller Support for Anki beta⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.addons", line 962, in onConfig
  File "/Users/kuan/Library/Application Support/Anki2/addons21/1898790263/contanki.py", line 98, in on_config
    ContankiConfig(focus, self.profile)
AttributeError: 'Contanki' object has no attribute 'profile'

**Comment by al099** [comment]
When I try to save my configurations, it says "Error: Couldn't load Left Stick icon for Joy-Con Left." and then nothing is changed/saved when I map my bottons. Please advise!

**Comment by roxgib** [comment]
You can find previous versions [here](https://github.com/roxgib/anki-contanki/releases). You probably want Beta 7. 

The latest beta required a change to the way profiles were stored. You old profile should have been automatically converted - check the profiles list in config, it should be there with "(converted)" appended to it.

I'll investigate the issue with saving.

**Comment by roxgib** [comment]
The error you are receiving should be fixed with [2915c2f](https://github.com/roxgib/anki-contanki/commit/2915c2f13a0ac5887083f54980338954ecd59202). I'm not 100% certain that this is related to the saving issue so I'll leave this open for now.

**Comment by roxgib** [comment]
Saving error was fixed by [2915c2f](https://github.com/roxgib/anki-contanki/commit/2915c2f13a0ac5887083f54980338954ecd59202)

**Comment by al099** [comment]
Thank you so much, really appreciate it!
