### ISSUE TITLE
Quick Select controls

### ISSUE THREAD

**Issue by kenf1** [roxgib/anki-contanki#33]
Is it possible to modify order of quick select controls and which button/flick will activate them?

**Comment by roxgib** [comment]
Probably at some point, it's not a priority for the moment tbh. If you really want you can open up Anki/addons21/1898790263/user_files/profiles/your-profile-name and edit the order of the items, I believe that should change the order in the menu.

**Comment by roxgib** [comment]
I don't think I'll actually keep this as planned, it would required redesigning the options page which is too much work to be worthwhile. At some point I'll move the config dialog to use Qt .ui files, which might be a good time to add this option.
