### ISSUE TITLE
Unable to get certain inherited controls to save

### ISSUE THREAD

**Issue by kenf1** [roxgib/anki-contanki#34]
Certain inherited controls will not save. No trend noticed thus far. Tried the following:

- changed single control (inherited), save, reopen program
- changed multiple controls (inherited), save, reopen program

Current workaround is set same control (non-inherited) to ones that will not save.

macOS, Anki Version ⁨2.1.54 (b6a7760c)⁩

**Comment by roxgib** [comment]
Thanks, fixed with [31169dc](https://github.com/roxgib/anki-contanki/commit/31169dc1dab5a8cdb9d53477fcea2949140a350b)
