### ISSUE TITLE
Error when trying to use addon

### ISSUE THREAD

**Issue by bendd76** [roxgib/anki-contanki#35]
Hi, I keep getting this error when i try and use the addon?

# Error

An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.

If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem.

When you've discovered the add-on that is causing the problem, please report the issue on the [add-ons section](https://forums.ankiweb.net/c/add-ons/11) of our support site.

Debug info:

Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1

Platform: Mac 13.0

Flags: frz=True ao=True sv=2

Add-ons, last update check: 2022-11-04 11:50:38

Add-ons possibly involved: ⁨Contanki - Controller Support for Anki beta⁩

Caught exception:

Traceback (most recent call last):

File "/Users/****/Library/Application Support/Anki2/addons21/1898790263/contanki.py", line 105, in on_config

ContankiConfig(focus, self.profile)

File "/Users/****/Library/Application Support/Anki2/addons21/1898790263/config.py", line 100, in __init__

self.options_page = OptionsPage(self)

File "/Users/****/Library/Application Support/Anki2/addons21/1898790263/config.py", line 239, in __init__

self.profile_bar = self.ProfileBar(parent)

File "/Users/****/Library/Application Support/Anki2/addons21/1898790263/config.py", line 309, in __init__

self.profile_combo.setCurrentIndex(p_list.index(self.profile.name))

ValueError: '8BitDo Zero' is not in list

**Comment by roxgib** [comment]
Thanks for reporting, this should be fixed with [70a0e99](https://github.com/roxgib/anki-contanki/commit/70a0e9964573487cda42615a246212e09a93d1ff) which will be in the next beta
