### ISSUE TITLE
overlay always on inhibits normal mouse clicks

### ISSUE THREAD

**Issue by smileIsmail** [roxgib/anki-contanki#36]
Hello,

Thanks for the add on it's really great and the overlays are really useful. I am using the latest add-on version from ankiweb, so the beta version 2.1.54~ I believe. I am using anki version Version ⁨2.1.54 (b6a7760c)⁩. I am also using a wired xbox 360 controller.

Checking the overlay always on check box immediately stops all mouse interactions with the "decks, add, browse [...]" menu and the decks and subdecks menu:
![image](https://user-images.githubusercontent.com/105790127/200200041-0b94db89-18c5-4ff7-9877-f412afa785ff.png)

Note: interaction with the main toolbar, i.e. the "File, Edit, View, [...]" menu remains in tact.

Not only regular mouse interactions with the mentioned menus are inhibited but also the mouse which is controlled by the controller cannot click either. This includes both right and left mouse clicks and even the mouse hover interactions such as the underline appearing when hovering over a deck or subdeck.

Hopefully this format was good and detailed enough. Thanks again!

**Comment by roxgib** [comment]
Thanks for reporting, I'll try to address this behaviour

**Comment by roxgib** [comment]
Fixed with [6f0ab20](https://github.com/roxgib/anki-contanki/commit/6f0ab20f9a3514b7be9d4ea4b35ef2d7d31fb3da)
