### ISSUE TITLE
Invalid Code 

### ISSUE THREAD

**Issue by eshaareza** [roxgib/anki-contanki#38]
Hello! Upon installing the Contanki Add-on, I am receiving this error:

1898790263: Invalid code, or add-on not available for your version of Anki.

I am using Anki version number Version ⁨2.1.47 (dc156f34)⁩. 

If anyone knows how I can fix this, please let me know! :)

**Comment by roxgib** [comment]
Hmm, looks like when I uploaded the last version I didn't include the older versions of Anki. I'll fix this, but I recommend updating to a newer version

**Comment by eshaareza** [comment]
Thank you so much! I updated and it works great :)
