### ISSUE TITLE
8BitDo Zero 2 - can't proceed on the question side of cards, but can on review...

### ISSUE THREAD

**Issue by chrisdyang** [roxgib/anki-contanki#39]
I'm using Contanki Beta 12 with an 8BitDo on Anki 2.1.51. I coded all my key assignments into a new profile, and everything works as expected EXCEPT when answering questions. In other words, I cannot use the controller to mark my flashcards as good/hard/again/easy at the question prompt, but can at the review prompt. Any help would be appreciated.

**Comment by roxgib** [comment]
Thanks for reporting this. The new beta I released yesterday should improve compatibility with the 8BitDo as I've now purchased one for testing, though I don't know if your issue is related to the controller you're using. If the new beta doesn't fix the issue, can you let me know what OS you're using?

**Comment by ColloidOncPressure121** [comment]
I have the same issue and I'm using Anki version  ⁨2.1.54 and windows. I've tried to change the settings, etc. spending hours to no avail. The issue first arose about 3 months ago when I updated to Anki version 2.1.54 6b. Providing a fix/clarifying would be huge Godsend!

**Comment by roxgib** [comment]
Sorry, I should have read the issue more carefully. Anki doesn't allow you to answer until flipping the card. You can use [this add-on](https://ankiweb.net/shared/info/850294128) to override the default behaviour - you might need to connect the assigned buttons to Contanki using a 'custom action' in the controller settings.
