### ISSUE TITLE
Xbox Series variant PID is missing

### ISSUE THREAD

**Issue by AuroraWright** [roxgib/anki-contanki#4]
My (original) Xbox Series controller has these IDs: Vendor: 045e Product: 0b13 which appear to be missing in controllerIDs.json, causing it to be recognized as a DualShock (for some reason?).
Adding the PID manually worked fine so far.
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/15571693/168427227-da0a5f80-1e20-45bc-8a73-be4f3b61d0b1.png">

**Comment by roxgib** [comment]
Thanks, I've added it to the list. If it doesn't recognise the ID it will try to guess the controller type based on the name and number of buttons, but looks like there was an error there where it wouldn't fall back to an Xbox controller of some kind if it couldn't figure it out, so instead fell back to the DualShock.

Unfortunately with the Xbox controllers the number of buttons isn't consistent within each generation so there are likely to be some misidentifications, but with that bug fixed at least it'll almost always pick an Xbox controller. 

FYI you can always pick the controller in the settings menu, and it should remember that choice when that controller is used in the future.
