### ISSUE TITLE
Cursor moving

### ISSUE THREAD

**Issue by LEGENPCCC** [roxgib/anki-contanki#40]
Hello, I am using this fabulous add-on on windows with X-box controller. When I am using it my cursor keeps moving to the left side of the window slowly.

**Comment by roxgib** [comment]
I'd suggest increasing the deadzone, which you can do in Tools > Controller Options. You may also be able to do it Windows settings.

**Comment by LEGENPCCC** [comment]
Thanks. It did not seem to work by increasing the deadzone, so I customized the right stick to "unassigned" from moving the cursor, and the cursor stopped slowly moving to the left now. I do not even know we can customize the buttons! Great add-one. 10/10

**Comment by roxgib** [comment]
Odd, usually it's a deadzone issue. Can I ask you to open up the Controller Options > Help, and share the info there?

**Comment by LEGENPCCC** [comment]
See the [add-on page](https://ankiweb.net/shared/info/1898790263) for some tips on using Contanki. If you're having trouble or have found a bug you can post on the [official support thread](https://forums.ankiweb.net/t/contanki-official-support-thread/) or the [GitHub issue tracker](https://github.com/roxgib/anki-contanki/issues). 

Please copy and paste the following information into your post:

Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-12-09 21:25:26

1 controller detected:
Xbox 360 Controller (XInput STANDARD GAMEPAD)
Buttons: 17
Axes: 4

**Comment by roxgib** [comment]
After a bit more investigation it seems that changes to the deadzones were not taking effect until restarting. I've fixed that with [fd1467b](https://github.com/roxgib/anki-contanki/commit/fd1467b8f45596d134de5a11a3bb91523d19c95b). Could be the reason changing the deadzones didn't work for you?
