### ISSUE TITLE
Two Scoll Up commands, cannot find Scroll down command

### ISSUE THREAD

**Issue by soisaws** [roxgib/anki-contanki#43]
![image](https://user-images.githubusercontent.com/120546220/207612897-5cbffb22-7d23-495a-ac4b-c74e077034f2.png)

**Comment by roxgib** [comment]
Oops, fixed with [97277f1](https://github.com/roxgib/anki-contanki/commit/97277f167bed5e7399bc0f9c969eb7e74550e4cc). Thanks for reporting!
