### ISSUE TITLE
Feature request: export settings & controller keybinds

### ISSUE THREAD

**Issue by kenf1** [roxgib/anki-contanki#44]
For export and re-import

**Comment by roxgib** [comment]
If you navigate to your Anki folder (should be called Anki2) and look for Anki2/addons21/1898790263/user_files/profiles you'll find your profiles, which you can copy across to a different computer. But I do agree it should be easier, I'll leave this open and look at adding that option.

**Comment by roxgib** [comment]
Add with 54fff79
