### ISSUE TITLE
Addon fails to load under Windows 11

### ISSUE THREAD

**Issue by Lolle2000la** [roxgib/anki-contanki#46]
I'm running Anki 2.49 and wanted to try using my Gullikit Kingkong 2 Pro controller (normal XInput controller, like XBox controller. However, on startup I get the following error. It seems to prevent the addon from working.
```text
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Contanki - Controller Support for Anki beta⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 230, in loadAddons
  File "C:\Users\Lolle\AppData\Roaming\Anki2\addons21\1898790263\__init__.py", line 6, in <module>
    from .contanki import Contanki
  File "C:\Users\Lolle\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 13, in <module>
    from .quick import QuickSelectMenu
  File "C:\Users\Lolle\AppData\Roaming\Anki2\addons21\1898790263\quick.py", line 17, in <module>
    from .actions import button_actions
  File "C:\Users\Lolle\AppData\Roaming\Anki2\addons21\1898790263\actions.py", line 10, in <module>
    from aqt.utils import tooltip, is_mac
ImportError: cannot import name 'is_mac' from 'aqt.utils' (C:\Program Files\Anki\aqt\utils.pyc)
```

**Comment by roxgib** [comment]
This should be fixed in the latest update, but unfortunately I don't have a Windows 11 PC to test on so it would be great if you could let me know if it's is working now.

**Comment by Lolle2000la** [comment]
I've tried it and it seems to work perfectly now. Recognized both my XBox one and Kingkong 2 Pro controller. Thank you for your work!

**Comment by roxgib** [comment]
Great, thanks. The problem was actually related to using Anki 2.49 (latest version is 2.56) but good to know it works on Windows 11
