### ISSUE TITLE
Display hint using controller

### ISSUE THREAD

**Issue by johtso** [roxgib/anki-contanki#48]
On all my language learning cards I use the built in `hint:` feature to hide the english translation unless I really need to check it.

Is it possible to reveal the hint using the gamepad?
Would I maybe need to use some kind of workaround like implementing the hint using a bit of javascript and listening for a keyboard shortcut?

**Comment by roxgib** [comment]
I use [this add-on](https://ankiweb.net/shared/info/1844908621) which adds keyboard shortcuts to show hints. From there you can add a "Custom Action" to Contanki for the shortcuts (G and H) and then assign a button to them. I know that's a little more work that just having it as a feature but generally I'll try to avoid duplicating other add-ons as it adds a lot of work.

**Comment by johtso** [comment]
I thought that some kind of solution with keyboard shortcuts might be the way.. thanks for showing me the way!
