### ISSUE TITLE
No button to program "Reveal Next" in cloze overlapping function. 

### ISSUE THREAD

**Issue by dmorris21** [roxgib/anki-contanki#55]
Is there an existing button to program on the DualShock 5 controller to be able to reveal next? Select Next does not work for some reason.

**Comment by roxgib** [comment]
Close overlapper [includes hotkeys](https://github.com/Glutanimate/cloze-overlapper/wiki/Use), so you can link those in Contanki by adding "Custom Actions" for each hotkey you want.
