### ISSUE TITLE
Zero2 button mapping wrong on Mac

### ISSUE THREAD

**Issue by akavi1** [roxgib/anki-contanki#56]
I am using an 8BitDo Zero2 remote to control Anki on MacOS Ventura. I tried connecting the controller using xinput, dinput, and the macOS input. and they all seem to have some issues with button mapping.

X input seems to work the best, except the A and B keys are switched and the X and Y keys are switched. 

Ex) going to Tools > Controller Options, setting the input to Zero 2 (X Input), and pressing A on the Controls screen highlights the B button; it should should highlight A

**Comment by bendd76** [comment]
I've got the exact same issue have you found a way to fix this?

**Comment by kiler129** [comment]
I think it's either solved already, or your configuration for buttons is wrong (like mine was initially). Make sure you set buttons both for "Review" tab AND the "Answer" tab. That way the answers will be marked properly:

![image](https://github.com/roxgib/anki-contanki/assets/1227834/94dba980-796c-42d5-87c3-ae262ab8a507)
![image](https://github.com/roxgib/anki-contanki/assets/1227834/7d0caf4d-7b61-45a8-9e66-a2a90974394b)

To be sure you're selecting answers you meant to, you can check https://ankiweb.net/shared/info/1084228676

**Comment by roxgib** [comment]
Apologies for the delay with fixing this, but it should now be resolved with the latest update. Note that the latest update only supports 2.1.66 and above.
