### ISSUE TITLE
8BitDo Zero 2 Controller detected as Xbox 360 controller on initial connection

### ISSUE THREAD

**Issue by raymond-bascal** [roxgib/anki-contanki#58]
When initially connecting an 8BitDo Zero 2 controller, Anki seems to detect it as a Xbox360 controller. This is usually fixed by me via going into controller options and changing the profile and input to the appropriate settings.

 I was wondering if there is a way to either force a default profile so it's always assuming I'm using this specific controller, or if it can detect the right type of controller on connection.

I'm using:
Windows 11
Anki Version 2.1.56

**Comment by AnKingMed** [comment]
hold A + start and it'll switch to mac mode or Y + start and it'll switch to switch mode (this worked best for me)

**Comment by flarbow** [comment]
this is happening to me as well. and switching it to mac or switch mode isnt fixing the issue. x mode is the only one working and it identifies it as an xbox 360 controller

**Comment by roxgib** [comment]
8BitDo controllers mascarade as other controllers for compatibility reasons. There is an option in the config "Detect 8BitDo Controllers" that will detect most (but not all) correctly. Note you can also change the controller manually in the config.
