### ISSUE TITLE
Cursor issue with second monitor

### ISSUE THREAD

**Issue by markhavemann** [roxgib/anki-contanki#59]
If you use a second monitor and it's to the right of your main monitor, any time you move the mouse cursor (with the right stick on an Xbox 360 controller), the mouse cursor will stick to the left side of the screen. It can still move up and down but as soon as you move the right joystick, it will jump to the left of the screen and stick there, not moving left or right.

This only happens when Anki is on the second monitor. The mouse cursor control works normally if Anki is on the main monitor.

I haven't tested this with a second monitor to the left of the main screen.

**Comment by roxgib** [comment]
Apologies for the delay in replying. Are you using Windows?

**Comment by roxgib** [comment]
This should be fixed with 9f063f0
