### ISSUE TITLE
Missing input options

### ISSUE THREAD

**Issue by RoninSai** [roxgib/anki-contanki#60]
I'm missing input options for my dual sense controller, such as again, hard, easy, and suspend. Any idea on why that is? I'm using the most up to date version of ContAnki and Anki Version ⁨2.1.56.

<img width="869" alt="Screenshot 2023-06-11 at 6 53 50 PM" src="https://github.com/roxgib/anki-contanki/assets/136286265/225f1adf-4bcb-484b-8742-383e806e3dc1">

<img width="869" alt="Screenshot 2023-06-11 at 6 54 03 PM" src="https://github.com/roxgib/anki-contanki/assets/136286265/bc58bf1e-b13f-4036-bcc2-10557c0bf79b">

**Comment by mobedoor** [comment]
You're on the wrong tab. Go from default to the review and question tab and set the relevant actions there.
