### ISSUE TITLE
8bitdo controller not detected

### ISSUE THREAD

**Issue by somedude317** [roxgib/anki-contanki#64]
Hi I'm using an 8bitdo ultimate controller, and it connects to my MacBook Air (2020, m1) and I tested on a website to make sure it is detected but in Anki the controller is not detected by the plugin and there is not controller detect option under tools.

**Comment by roxgib** [comment]
Apologies for the delay in responding. I've added support for the 8BitDo Ultimate for inclusion in the next update. That said, it should be been detected regardless even if it was identified as the wrong controller, so I'll leave this open and have you report back after the next update.
