### ISSUE TITLE
Joycon - controls mapping

### ISSUE THREAD

**Issue by losingwayssss** [roxgib/anki-contanki#67]
I am using the switch joycon and I am trying to assign the "replay audio [inherited]" function to another button but failed to do so.
What I can is assign "replay audio" to another button, but it won't play the audio in the back when I am in the front, which "replay audio [inherited]" does that. Any solution or workaround will be very much appreciated because it's very hard to get the joystick to work properly most of the time.  Thanks!

![anki](https://github.com/roxgib/anki-contanki/assets/149228815/c673f491-cff5-46a1-b789-3f4b6536c872)

**Comment by roxgib** [comment]
If I've understood you correctly, you want the audio from the front of the card to also play on the back. This requires that the audio be on both sides, front and back. The 'Replay Audio' action will simply play the audio that's on the currently shown side of the card, so if there's no audio on the back, nothing will play. You can find more information [in the manual](https://docs.ankiweb.net/templates/intro.html), or post on the forums if you need more help.

If I've misunderstood your problem, you can still reply here and I'll reopen it.

I do realise that the sticks are less than reliable in button mode, they used to work better but some changes seem to have been made to the API which limits the polling rate. Hopefully I can address this, but so far it's been a bit tricky to track down the problem.

**Comment by losingwayssss** [comment]
Thanks for your reply.  So, I did tried putting the audio at the front, the "Replay audio" doesn't work either, funny enough it only does its job AFTER I reviewed the back, which doesn't have audio attached to the back. 

While "replay audio [inherited]" key does the job both front, and back, without a problem. 

![anki](https://github.com/roxgib/anki-contanki/assets/149228815/db0b819b-0a7f-416c-990e-90616ea33bc7)

![Anki 2](https://github.com/roxgib/anki-contanki/assets/149228815/5d1ceb27-ce6b-4aed-a4f3-715fa577cff2)

**Comment by roxgib** [comment]
Okay, it's quite odd that the behaviour is different. The inherited action should behave identically to the original action. I haven't been able to reproduce the issue, so I'll grab some more info from you. Can I get you to click the "Help" button in the Controller Options dialog and paste the information here. Can you also look at the deck options and tell me if "Skip question when replaying answer" is toggled?

**Comment by roxgib** [comment]
Also, do the actions appear the same in the control overlays, whether inherited or not?

**Comment by losingwayssss** [comment]
Thanks for your help. 

Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-30 08:20:33

1 controller detected:
Wireless Gamepad (STANDARD GAMEPAD Vendor: 057e Product: 2007)
Buttons: 17
Axes: 2
![anki](https://github.com/roxgib/anki-contanki/assets/149228815/7d739235-ea6e-4dfc-bc21-e3332bba6275)

Sorry, not sure if I understand your last question, which control overlays to be exact?

**Comment by roxgib** [comment]
Sorry, did not mean to close it again!

The control overlays are usually assigned to the right trigger, they appear to remind you which buttons map to which actions

**Comment by losingwayssss** [comment]
Yes, the same issue occurred. However, interestingly, the "replay audio [inherited]" didn't appear on the control overlays but it works.
![anki](https://github.com/roxgib/anki-contanki/assets/149228815/c89c21a0-66fe-4032-853f-d454be463466)
![Untitled2](https://github.com/roxgib/anki-contanki/assets/149228815/19168615-8228-47ae-adb9-fbcf758679b2)
![asdasd](https://github.com/roxgib/anki-contanki/assets/149228815/65e3a3e5-b167-430f-aebc-c296de1a026a)

**Comment by roxgib** [comment]
I've just published a [new release](https://github.com/roxgib/anki-contanki/releases/tag/v0.10.0-beta) (it's not available on Ankiweb yet). Can you give that a try? It doesn't contain a specific fix but there are a lot of changes to related parts of the codebase, so worth checking to see if it helped.

**Comment by losingwayssss** [comment]
Tried it, it's the same behaviour. I appreciate your help but it's not the end of the world and I still enjoy using it daily obviously!

**Comment by roxgib** [comment]
I've just released a new version that fixes the issue of actions assigned to buttons not appearing in the overlay. Please give that a try, might give us a clue.

The other possibility is that your profile file got mangled in a previous update, so perhaps try with a new profile.
