### ISSUE TITLE
Axis Roles Options

### ISSUE THREAD

**Issue by spartandrew18** [roxgib/anki-contanki#69]
Hi,

I was wondering why the Axis Roles options does not allow assigning the same function to 2 different joysticks? For example on the iPad I can scroll up and down vertically with both the left and right joystick. However, when I try to attempt this on the PC it only allows vertical scrolling to the last assigned joystick regardless of having both joysticks enabled to the same function.

Is this a bug? Can we add it as a feature?

![image](https://github.com/roxgib/anki-contanki/assets/66539077/057d3b1d-f5e2-4115-a8e0-499903a2103a)

**Comment by roxgib** [comment]
Indeed it's a bug. Good catch, thanks for reporting! Fixed with [0b8c513](https://github.com/roxgib/anki-contanki/commit/0b8c5136079406497085cb1bbeea6952bc7fff26).

**Comment by spartandrew18** [comment]
> Indeed it's a bug. Good catch, thanks for reporting! Fixed with [0b8c513](https://github.com/roxgib/anki-contanki/commit/0b8c5136079406497085cb1bbeea6952bc7fff26).

Will the addon be updated to reflect this change?

**Comment by roxgib** [comment]
I've just released a new update with this fix included
