### ISSUE TITLE
8BitDo Zero 2 dpad buttons are not working

### ISSUE THREAD

**Issue by aguyfromsector2814** [roxgib/anki-contanki#73]
Similar to issue #72. Tried updating controller firmware, deleting and re-downloading addon, messing with controller bindings, tried both X input and D input, tried wired connection vs BT, nothing has fixed it.

**Comment by roxgib** [comment]
Thanks for reporting this. I have just released a [new beta](https://github.com/roxgib/anki-contanki/releases/tag/v0.11-beta), which will not be on AnkiWeb for a few days at least, that lets you reassign controls. Please give that a try and let me know if it addresses the issue.
