### ISSUE TITLE
Scrolling with JoyCon causes failure of add-on

### ISSUE THREAD

**Issue by masonofa** [roxgib/anki-contanki#74]
I am using a switch JoyCon. I just updated to the latest version of Anki today and now have problems with this add-on. I can connect my controller fine and use it to flip cards and answer, but once I try to scroll like I used to be able to, somehow I lose all actions. I can no longer flip, answer, etc. once I try to scroll. The add-on is essentially disabled after I try to scroll. I haven’t changed any settings in the Options menu. Usually when I first connect the controller, it is recognized as a 360 controller, but I just manually switch it to JoyCon in the menu. Here’s my debug info.

Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-03 09:48:23

3 controllers detected:
Xbox 360 Controller (XInput STANDARD GAMEPAD)
Buttons: 17
Axes: 4

Unknown Gamepad (Vendor: 045e Product: 09cf)
Buttons: 0
Axes: 3

Wireless Gamepad (STANDARD GAMEPAD Vendor: 057e Product: 2007)
Buttons: 17
Axes: 2

**Comment by masonofa** [comment]
Adding some screenshots that will hopefully be helpful. You'll notice my overlay shows the stick can scroll the page even though I have it unassigned now in the options menu (this is a change from my usual settings but was something I noticed as I was tinkering with the settings to troubleshoot the root of the problem).
![image](https://github.com/roxgib/anki-contanki/assets/124424726/f85ab974-7fd9-4de7-bb0f-f744af21df25)
![image](https://github.com/roxgib/anki-contanki/assets/124424726/652f7eea-aefe-4962-9c5f-8020761fca8a)

**Comment by roxgib** [comment]
This should be fixed in the latest version, please let me know!
