### ISSUE TITLE
Button icons in config not flashing for some users

### ISSUE THREAD

**Issue by roxgib** [roxgib/anki-contanki#75]
The buttons in the config light up when pressed, like this:
<img width="611" alt="Screenshot 2023-12-07 at 7 57 55 pm" src="https://github.com/roxgib/anki-contanki/assets/33942237/755ec8e5-8ce4-4b22-8095-4443220e8461">

@x51mon reports this [doesn't work](https://github.com/roxgib/anki-contanki/issues/72#issuecomment-1841191178), but unfortunately this wasn't picked up until the 'Controller' tab was added because that tab actually relies on the icons lighting up. Most likely it's a Qt issue with updating the icon pixmap on some platforms.

**Comment by x51mon** [comment]
> Latest is now Beta 21

Yes that is working great now, thank you.

**Comment by roxgib** [comment]
Great, thanks for testing
