### ISSUE TITLE
8bitdo Micro not detecting

### ISSUE THREAD

**Issue by nvkottap** [roxgib/anki-contanki#76]
my 8bitdo micro is connected but unable to be recognized by contanki

**Comment by roxgib** [comment]
My Micro arrived this morning, so I'll get to adding support for it in the next few days.

**Comment by AnKingMed** [comment]
www.theanking.com/controller.  I've got it working for me

**Comment by roxgib** [comment]
Has now finally made it into a published version!

**Comment by nvkottap** [comment]
Awesome it works! May have to just adjust my window size but on mac the bottom of the control adjustment screen extends beyond the bottom of the screen.

<img width="1440" alt="Screenshot 2024-01-17 at 8 13 34 AM" src="https://github.com/roxgib/anki-contanki/assets/119903296/b1cd5b8a-157f-40d7-902f-172104871ac4">

**Comment by roxgib** [comment]
Hmmm, I might have to squeeze them closer together or make it scrollable

**Comment by roxgib** [comment]
> on mac the bottom of the control adjustment screen extends beyond the bottom of the screen

This behaviour should be improved in the next version
