### ISSUE TITLE
Controller not detected

### ISSUE THREAD

**Issue by shahram7** [roxgib/anki-contanki#79]
Hi there,
I have set up my Anki software on a web-based Ubuntu-KDE environment called ["webtop"](https://hub.docker.com/r/linuxserver/webtop) using a Docker container on my personal server. I access Anki by opening a browser tab on my laptop. I use an 8BitDo SN30 Pro controller to interact with Anki, which is connected to my laptop via Bluetooth. Therefore, it's understandable that your add-on is unable to detect the controller since it is connected to a different machine.
Currently, I have installed a software called "JoyToKey" on my laptop. This software allows me to remap the buttons on my controller so that I can use it with Anki. However, I would greatly appreciate it if you could provide any suggestions or alternative methods that would enable me to use your Add-on.
![image](https://github.com/roxgib/anki-contanki/assets/34509793/f951a5d6-f2bd-4d5f-a021-a7a0d6f3df7d)

Best Regards,
Shahram

**Comment by roxgib** [comment]
Unless the software you're supporting has a way to pass USB devices through to the OS that is running Anki (which seems unlikely if you're accessing it through a web browser) I don't see a way to make this work. It interacts with controllers through the HTML5 Gamepad API, so if it works with that it'll work with Contanki.
