### ISSUE TITLE
Updated now Not Working :-(

### ISSUE THREAD

**Issue by stevetdrums** [roxgib/anki-contanki#8]
Hi All
Just updated this FANTASTIC add on, and now it's not working at all. Been using an XBox 360 style controller (white). Was working perfectly before updating, now this error comes up below. Please help as this app was a gamechanger!!!

------

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.45 (355e66e8) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-06-27 07:55:39
Add-ons possibly involved: ⁨Contanki - Controller Support for Anki beta⁩

**Comment by roxgib** [comment]
Thanks for letting me know, I've released an updated version with [this issue fixed](https://github.com/roxgib/anki-contanki/commit/a24ee22beb55f880ba4898fe87324ed2768dd413). You should be prompted to update next time you open Anki. If you could confirm that this fixes the issue for you that'd be great.

**Comment by stevetdrums** [comment]
Thank you very much! I can't seem to get it to work with the latest release download from the add ons site for Anki, but I managed to find the beta version on GitHub which I downloaded and that works like a treat.

**Comment by roxgib** [comment]
The version on AnkiWeb should now be the latest version - turns out there's [an issue](https://forums.ankiweb.net/t/add-on-max-version-needs-updating-on-ankiweb/21059) with version numbers on AnkiWeb and the version I uploaded there didn't upload the first time. Big thanks for letting me know about that as well, I hadn't realised the first time that it hadn't uploaded successfully.
