### ISSUE TITLE
Connecting Switch Pro no buttons detected

### ISSUE THREAD

**Issue by frankfzhou** [roxgib/anki-contanki#82]
When I connect my Switch Pro via either Bluetooth or USB, it detects three different controllers, and I can't control anything. The majority of the buttons are also not detected.

Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.22631
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2024-01-21 20:49:46

3 controllers detected:
Unknown Gamepad (Vendor: 045e Product: 09af)
Buttons: 0
Axes: 3

Unknown Gamepad (Vendor: 045e Product: 09a6)
Buttons: 0
Axes: 3

Wireless Gamepad (STANDARD GAMEPAD Vendor: 057e Product: 2009)
Buttons: 18
Axes: 4

![image](https://github.com/roxgib/anki-contanki/assets/149561575/48cfc445-8ff5-4a90-942a-93651cd7ac9e)

**Comment by frankfzhou** [comment]
Oh, I think I fixed it. I had to go in Tools of the Anki main menu and choose the right controller
![image](https://github.com/roxgib/anki-contanki/assets/149561575/d09bf10f-7411-4763-8d2a-2d5f87f3d7f2)

**Comment by roxgib** [comment]
Thanks for reporting. A few controllers also present one or more 'ghost' controllers that the add-on should ignore. I've added the ones from the Switch Pro controller to the list to be ignored in [7eedea0](https://github.com/roxgib/anki-contanki/commit/7eedea03d25ce52acd3d5ea48385d6300016677b)
