### ISSUE TITLE
No mapping for the 8BitDo Lite 2

### ISSUE THREAD

**Issue by brookebelanger** [roxgib/anki-contanki#84]
Getting super for this controller so you could use the joysticks to navigate the mouse would be a amazing!

**Comment by roxgib** [comment]
It will be aded in the next update!

**Comment by roxgib** [comment]
My Lite 2 arrived today. Unfortunately it seems that 8BitDo has not included support for X input mode, only D input mode. Other than an annoying button mapping, the D-pad is completely non-functional. Other than that it's working nicely.
