### ISSUE TITLE
Contanki Windows Screen slightly off screen

### ISSUE THREAD

**Issue by winterfey** [roxgib/anki-contanki#87]
The "Contanki Options" window in Anki is slightly off my laptop screen. So I can't see the buttons at the very bottom of the page to save settings etc. I'm stuck at the "default" buttons and the addon is basically unusable. I've tried to resize the window and move the window up but this is not possible. I even hid my taskbar but it made no difference. Any advice on what I can do?

**Comment by roxgib** [comment]
Thanks, seems the new page on the config dialog is taking up too much space with some controllers. Should be fixed with [89ce6c4](https://github.com/roxgib/anki-contanki/commit/89ce6c47fc23bcde3e1442f7a96a2489630e0de9).
