### ISSUE TITLE
[Feature Request] Any way to support other controller schemes?

### ISSUE THREAD

**Issue by tokisuno** [roxgib/anki-contanki#88]
Title. I am using an iBuffalo SNES USB controller, and it's really confusing trying to set this up with my own custom controls when what's forced is the playstation layout. I'm used to emulation software where you have to manually map every button, so this feels very weird to use. Any advice or acknowledgement towards this would be great!

**Comment by roxgib** [comment]
Tools > Controller Options allows you to remap controls. The SNES controller is supported, so selecting that from the top right drop down will give you the correct buttons. I would then create a new profile based on the SNES default layout, or you can just set up yourself from the controls tab.

Down the bottom of the Options dialog there is a 'Help' button. Clicking that will give you some debug information, including the Device ID of your controller. If you post that here I'll add it so this controller is automatically detected as a SNES controller.

**Comment by tokisuno** [comment]
```Anki 23.12.1 (1a1d4d54) (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Linux-6.7.4-arch1-1-x86_64-with-glibc2.39

1 controller detected:
USB,2-axis 8-button gamepad (STANDARD GAMEPAD Vendor: 0583 Product: 2060)
Buttons: 16
Axes: 2```
