### ISSUE TITLE
Addon dosen't load on startup

### ISSUE THREAD

**Issue by Vilhelm-Ian** [roxgib/anki-contanki#92]
When I run anki through the terminal I get the following error.

`JS error :1 Uncaught ReferenceError: get_controller_info is not defined`

The addon dosen't work wether I open it through terminal or not.

When I try to press a button on the controller I get the following error

`Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 157, in _onCmd
  File "aqt.webview", line 680, in _onBridgeCmd
  File "_aqt.hooks", line 5415, in __call__
  File "/home/jovan/.local/share/Anki2/addons21/1898790263/contanki.py", line 146, in on_receive_message
    funcs[func](*args)
  File "/home/jovan/.local/share/Anki2/addons21/1898790263/contanki.py", line 383, in on_connect
    self.profile = get_profile(profile)
  File "/home/jovan/.local/share/Anki2/addons21/1898790263/contanki.py", line 116, in profile
    self.overlay = ControlsOverlay(mw, profile)
  File "/home/jovan/.local/share/Anki2/addons21/1898790263/overlay.py", line 72, in __init__
    for index, button in sorted(
  File "/home/jovan/.local/share/Anki2/addons21/1898790263/overlay.py", line 74, in <lambda>
    key=lambda inputs: BUTTON_ORDER.index(inputs[1]),
ValueError: '' is not in list

unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0
unhandled bridge cmd: contanki::poll::false,false,false,false,false,false,false,false,false,false,false,false,false,false,false::0,0,0,0,0,0,0,0`

I am using sway

**Comment by roxgib** [comment]
Thanks for reporting, this should be fixed in the latest update
