### ISSUE TITLE
Left & Right Stick Functionality Broken After Update

### ISSUE THREAD

**Issue by giongioselvy** [roxgib/anki-contanki#95]
I've been using the add-on for a few weeks now and it's been working flawlessly. However, after the update released today, both the left and right sticks have stopped working. Previously, these buttons were used to navigate through decks (moving forward and backward), which was a feature I relied on heavily. Would it be possible to investigate this issue? Thank you for your continued development efforts.

**Comment by masonofa** [comment]
I am having the same issue now with my JoyCon R. My stick was mapped to scroll up and down, but this is nonfunctional currently.

Debug info:
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22621

**Comment by roxgib** [comment]
Thanks for reporting, this should now be fixed

**Comment by giongioselvy** [comment]
> Thanks for reporting, this should now be fixed

It is indeed. Thank you!
